### ISSUE TITLE
模型方面的问题

### ISSUE THREAD

**Issue by Deicide-LC** [huaifeng1993/FashionAI_Key_Points_Detection#11]
你好，关于模型我有一些疑惑：这个模型可以将多种服装训练成一个模型吗，也就是说输入任何一种服装用这个模型进行测试都可以生成对应的关键点。还是说将config文件中NUM_CLASSES改成1+5就可以了

**Comment by huaifeng1993** [comment]
如果需要训练成一个模型，代码需要修改修改。不过我没改过。现在是训练了5个模型。你可以看这份代码。这位大佬的模型写的比较好，得分也高。https://github.com/HiKapok/tf.fashionAI
