### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by Zumbalamambo** [huaifeng1993/FashionAI_Key_Points_Detection#2]
How did you annotate? Can you please share the sample dataset?

**Comment by huaifeng1993** [comment]
I put the dataset on baidu Clound .you can download the data from here https://pan.baidu.com/s/1mafQ8N9G1PReGpOgLM7LQw or  download it  from FashionAI Global Challenge—Key Points Detection of Apparel https://tianchi.aliyun.com/competition/introduction.htm?spm=5176.100150.711.5.44642009A2ttwy&raceId=231648&_lang=en_US

**Comment by Zumbalamambo** [comment]
@huaifeng1993 Thank you so much . the file size is too large so it is asking for some software to install. However the software is in chinese language so I couldnt read it. Can you please provide a small dataset ?

**Comment by huaifeng1993** [comment]
@Zumbalamambo sorry for my negligence of the trouble created by the software. I think that i can send the dataset to you by email.could you leave me your email address?

**Comment by Zumbalamambo** [comment]
@huaifeng1993 thank you so much. Please share it in my email zumbalamambo@gmail.com .
