### ISSUE TITLE
SOME PROBLEMS ABOUT YOUR CODE

### ISSUE THREAD

**Issue by hongge831** [huaifeng1993/FashionAI_Key_Points_Detection#3]
您的代码要求cudnn7的吗？我的电脑装的是cudnn6，运行时报cudnn版本不匹配？您能帮我解答吗？

**Comment by huaifeng1993** [comment]
Installing TensorFlow on Ubuntu

This guide explains how to install TensorFlow on Ubuntu. These instructions might also work on other Linux variants, but we have only tested (and we only support) these instructions on Ubuntu 14.04 or higher.
Determine which TensorFlow to install

You must choose one of the following types of TensorFlow to 

    TensorFlow with CPU support only. If your system does not have a NVIDIA® GPU, you must install this version. Note that this version of TensorFlow is typically much easier to install (typically, in 5 or 10 minutes), so even if you have an NVIDIA GPU, we recommend installing this version first.
    TensorFlow with GPU support. TensorFlow programs typically run significantly faster on a GPU than on a CPU. Therefore, if your system has a NVIDIA® GPU meeting the prerequisites shown below and you need to run performance-critical applications, you should ultimately install this version.

NVIDIA requirements to run TensorFlow with GPU support

If you are installing TensorFlow with GPU support using one of the mechanisms described in this guide, then the following NVIDIA software must be installed on your system:

    CUDA® Toolkit 8.0. For details, see NVIDIA's documentation. Ensure that you append the relevant Cuda pathnames to the LD_LIBRARY_PATH environment variable as described in the NVIDIA documentation.
    The NVIDIA drivers associated with CUDA Toolkit 8.0.
    cuDNN v6. For details, see NVIDIA's documentation. Ensure that you create the CUDA_HOME environment variable as described in the NVIDIA documentation.
    GPU card with CUDA Compute Capability 3.0 or higher. See NVIDIA documentation for a list of supported GPU cards.
tensorflow1.3版本，可以支持cudnn6.0可以查看一下tenflow安装的版本的要求。
