### ISSUE TITLE
download  the dataset find unzip is error

### ISSUE THREAD

**Issue by SmallMunich** [huaifeng1993/FashionAI_Key_Points_Detection#4]
Hi@huaifeng1993,
I see about the ReadMe.
project 
  |--README.md  
  |--data  
     |--round2test
     |--train   
        |--Images  
        |--Annotations  
           |--annotation.csv  
           |--train.csv 
           |--test_b.csv  		   
           |--test_a.csv
           |--data_scaling.csv
           |--data_flip_up_down.csv
  |--code   
  |--submit   
     |--类别_resutl_b.csv  
     |--test.csv  
  |--model  
     |--mask_rcnn_类别.h5  
  |--logs 

I download the dataset from the baiduCloud finished. However, I unzip the dataset named "衣服关键点检测" , I cannot find the file folder. I want to know that this '衣服关键点检测' is trainning data?  Is the follow down ? 
  |--data  
     |--round2test
     |--train   
        |--Images  
        |--Annotations  
           |--annotation.csv  
           |--train.csv 
           |--test_b.csv  		   
           |--test_a.csv
           |--data_scaling.csv
           |--data_flip_up_down.csv

**Comment by huaifeng1993** [comment]
the data from baiduCloud just fit for round  one and i have not upload the round two dataset.The code in single_train.py 
```     
if category=='train':
            data_path = '../data/train/'
            annotations = pd.read_csv('../data/train/Annotations/annotations.csv')
            annotations = annotations.append(pd.read_csv('../data/train/Annotations/train.csv'), ignore_index=True)
            annotations = annotations.append(pd.read_csv('../data/train/Annotations/test_a.csv'), ignore_index=True)
            annotations = annotations.append(pd.read_csv('../data/train/Annotations/data_scaling.csv'), ignore_index=True)
            annotations = annotations.append(pd.read_csv('../data/train/Annotations/data_flip_up_down.csv'), ignore_index=True)
elif category=='val':
           data_path = '../data/val/'
annotations = pd.read_csv('../data/val/test_b.csv')'  
```
should be rewrite for the dataset in baiduCloud .

**Comment by SmallMunich** [comment]
thanks!
