### ISSUE TITLE
data数据集怎么使用？

### ISSUE THREAD

**Issue by tanzf** [huaifeng1993/FashionAI_Key_Points_Detection#5]
下载了你的data，但是是.gz后缀名文件，解压开之后生成文件类型为“文件”的文件，不知道怎么使用？？？

**Comment by huaifeng1993** [comment]
解压后应该是几个包含文件的文件夹才对。你再次解压看一看，如果没有你留下你的邮箱。

**Comment by tanzf** [comment]
还是没有，生成了类型为“文件”的文件，在linux系统跟win系统下解压都是这种情况，tanzfzb@163.com，麻烦您发我一份，谢谢

**Comment by huaifeng1993** [comment]
已经发你邮箱了。第一轮数据完整发送过去，第二轮训练数据单个文件超过上传限制，没办法发给你。

**Comment by tanzf** [comment]
好的，非常感谢

**Comment by wulixunhua** [comment]
@huaifeng1993  可以给我发一份吗？  383109759@qq.com

**Comment by monk678** [comment]
您好，我遇到了同样的问题【下载了你的data，但是是.gz后缀名文件，解压开之后生成文件类型为“文件”的文件，不知道怎么使用？？？】
请问你能否发送一份数据集给我，shulisiyuan@163.com
非常感谢！
