### ISSUE TITLE
只能识别一条裙子的关键点，怎么接触这个限制

### ISSUE THREAD

**Issue by ivoxx** [huaifeng1993/FashionAI_Key_Points_Detection#7]
￼
![zz](https://user-images.githubusercontent.com/26004978/44455763-6d2bde80-a631-11e8-8b06-95c09497a364.jpg)

**Comment by ivoxx** [comment]
在config中更改，已经解决了

**Comment by Deicide-LC** [comment]
@ivoxx 这个模型可以识别多个裙子吗，config如何改？
